İlk commit
ETOTEK-Mobil/ahmet_odev pull request #2
Opened 2024-11-24 05:28 UTC by ahmetcng33

2024-11-24 07:25 UTC, berkeenesakt requested changes
Eline sağlık eklediğim yorumları düzelttikten sonra mergeleyebiliriz bunu.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/hafta_1_view.dart
> +//!Burası ne işe yarıyor bulamadım, yardıma açığım.
Burası biraz fazla olmuş Widget build fonksiyonu altındaki `return Scaffold(...);` widgetini kopyalayıp Hafta1View içindeki widget build fonksiyonu altındaki `return MaterialApp(...);` ile değiştirirsen tamamdır sonra bu widgetı silebilirsin.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/hafta_1_view.dart
> +    return MaterialApp(
Burda material appe ihtiyacımız yok ben lib/main.dart altında bir material app oluşturdum zaten projede sadece onu kullanacağız. Aşağıdaki yorumda bahsettiğim widgetı buraya yapıştırabilirsin.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/hafta_1_view.dart
> +class AppSize {
Ödev dosyasında bahsetmeyi unutmuşum ben `lib/core/constants/app_sizes.dart` dosyasında bu classı oluşturdum bunu silip onu kullanabilirsin. Ayrıca class tanımlarken view dosyası yerine ayrı bir dosya oluşturman gerekiyor

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/hafta_1_view.dart
> +import 'package:flutter_application_1/ui/view/pages/column_raw_stack_page.dart';
importlardaki `package:flutter_application_1` i `package:odev` olarak degistirmen lazım

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/result_page.dart
> +  @override
Sayfa3 un parametreyi istemesi için bu satırı eklemen lazım
` const Sayfa3({Key? key, required this.counterValue}) : super(key: key);`

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/stage_management_page.dart
> +class AppSize {
classları her dart dosyasında tanımlamana gerek yok tek bir dosyada tanımlayıp hep aynı classı kullanmamız gerekiyor. Bu app size classının amacı zaten tüm boyutları tek bir classta toplayabilmek

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/result_page.dart
> +class Sayfa3 extends StatelessWidget{
Sayfaları ya da classları herhangi bir şeyi isimlendirirken dosya adıyla aynı olması gerekiyor yani bunun adı ResultPage olmalı.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/column_raw_stack_page.dart
> +class Sayfa1 extends StatelessWidget{
Sayfaları ya da classları herhangi bir şeyi isimlendirirken dosya adıyla aynı olması gerekiyor yani bunun adı ColumnRowStackPage olmalı.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/stage_management_page.dart
> +class Sayfa2 extends StatefulWidget {
Sayfaları ya da classları herhangi bir şeyi isimlendirirken dosya adıyla aynı olması gerekiyor yani bunun adı StateManagementPage olmalı.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/result_page.dart
> +  @override
override ı silebilirsin

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/stage_management_page.dart
> +          title: Center(
AppBarda titleı center ile sararsan o yazı ekranın tam ortasında olmaz. Bunun yerine AppBar altındaki centerTitle parametresini true yapman lazım

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/column_raw_stack_page.dart
> +        // Positioned(
Bu sayfada ortaya yuvarlak yerleştirebilmen için bu yorum satırındaki kodu bunla değiştirip

`Center(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.purple,
                shape: BoxShape.circle,
              ),
              width: 100,
              height: 100,
              child: const Center(
                child: Text("Stack"),
              ),
            ),
          ),`

Stack widgetinin içine taşırsan olur burası.

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/column_raw_stack_page.dart
> +                flex: 50,
flexleri 2/1/1 yapmak daha kolay olur

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/result_page.dart
> +        child: Text("$counterValue"),
Burayı direkt counterValue olarak değiştirebilirsin

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/result_page.dart
> +import 'package:flutter/cupertino.dart';
Bu importu kaldırabilirsin

2024-11-24 07:25 UTC, berkeenesakt commented on lib/ui/view/hafta_1/pages/stage_management_page.dart
> +            Container(
Burada padding ile sabit bir değer belirleyip merkezlemek diğer cihazlarda sıkıntı çıkarabilir. Paddingi silip columna `mainAxisAlignment: MainAxisAlignment.center` parametresini eklemen lazım.

2024-11-29 18:55 UTC, ahmetcng33 commented
Berke tekrar hataları düzeltip push yapmayı denedim olup olmadığı hakkında bilgilendirme yapabilir misin ?

2024-12-01 04:08 UTC, merged